# Generated by Django 2.2.7 on 2019-12-17 06:16

import ClientDashboard.models
import ClientDashboard.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_appointment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='child_sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WalkinCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='email')),
                ('mobile_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile phone')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, verbose_name='Project Name')),
                ('project_images', models.FileField(blank=True, null=True, upload_to=ClientDashboard.models.content_file_name, verbose_name='Project Images')),
                ('project_number', models.CharField(max_length=10, verbose_name='project Number')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('0-5', '0-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41-45', '41-45'), ('46-50', '46-50'), ('51-55', '51-55'), ('56-60', '56-60'), ('61-65', '61-65'), ('66-70', '66-70')], max_length=10, verbose_name='Experience')),
                ('qualification', models.CharField(choices=[('UG', 'UNDER GRADUATE'), ('G', 'GRADUATE'), ('PG', 'POST GRADUATE'), ('PhD', 'PhD')], max_length=20, verbose_name='Qualification')),
                ('budget', models.CharField(choices=[('0-10', '0-10'), ('11-20', '11-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('61-70', '61-70'), ('71-80', '71-80'), ('81-90', '81-90'), ('91-100', '91-100')], max_length=20, verbose_name='Budget')),
                ('prefix', models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MS', 'MS'), ('MX', 'MX')], max_length=3, verbose_name='Prefix')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=10, verbose_name='Gender')),
                ('mobile_phone', models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile phone')),
                ('secondary_phone', models.CharField(max_length=10, null=True, verbose_name='Secondary phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('about_me', models.CharField(blank=True, max_length=250, verbose_name='About me ')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=ClientDashboard.models.content_file_name, verbose_name='Profile Picture')),
                ('location', models.CharField(max_length=30, verbose_name='location')),
                ('client', models.BooleanField(default=0, verbose_name='Client')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.sub_category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.CharField(max_length=10, verbose_name='clicks')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesProposalsUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.FileField(upload_to=ClientDashboard.models.change_file_path, validators=[ClientDashboard.validations.validate_file_extension], verbose_name='Invoices')),
                ('proposals', models.FileField(upload_to=ClientDashboard.models.change_file_path, validators=[ClientDashboard.validations.validate_file_extension], verbose_name='Proposals')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice_and_proposals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoice_and_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250, verbose_name='Feedback')),
                ('rating', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, verbose_name='rating')),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=30, verbose_name='Design project Name')),
                ('design_images', models.FileField(blank=True, null=True, upload_to=ClientDashboard.models.content_file_name, verbose_name='Design Images')),
                ('design_number', models.CharField(max_length=10, verbose_name='Design Number')),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeisgnUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=30, verbose_name='Design project Name')),
                ('design_images', models.FileField(upload_to=ClientDashboard.models.content_file_name)),
                ('date_time', models.DateField(blank=True, null=True, verbose_name='Actual BRS Start Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_designs', to=settings.AUTH_USER_MODEL)),
                ('design_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.child_sub_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=100, unique=True, verbose_name='Confirmation Code')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='child_sub_category',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.sub_category'),
        ),
        migrations.CreateModel(
            name='AppointmentScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.Appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
