# Generated by Django 2.2.7 on 2019-12-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentscheduler',
            name='slots_booked',
        ),
        migrations.RemoveField(
            model_name='appointmentscheduler',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='feedbackrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentScheduler',
        ),
        migrations.DeleteModel(
            name='FeedBackRating',
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
    ]
