# Generated by Django 2.2.7 on 2019-12-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0002_auto_20191218_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='child_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ClientDashboard.child_sub_category'),
            preserve_default=False,
        ),
    ]
